### PR TITLE
Add side maps for Seaskipper, and more Quests

### PR DESCRIPTION
**Pull request by magicus**
Quests:

* Deja Vu
* King's Recruit
* Misadventure on the Sea

### CODE REVIEW

**Comment by Incompleteusern** [comment]
On a roll!

**Review by Incompleteusern — CHANGES_REQUESTED** [review]
However, please manually crop out all off map (flat) regions, as little as it is, if possible.

**Comment by magicus** [comment]
What do you mean? Are you refering to the masks? They are there to hide the "ugly" parts.

**Comment by Incompleteusern** [comment]
Im referring to the flat terrain such as the portion of the village in one of the images. Wynncraft would likely be happier if that is not present.

**Comment by magicus** [comment]
This is how it looks like when it will be presented to the user:
https://github.com/Wynntils/WynntilsWebsite-API/pull/15

**Comment by magicus** [comment]
What you see here is the raw data as grabbed directly from journeymap, plus the masks I've created to filter out the "ugly" parts, plus the bounding boxes and names for each individual side map.

**Comment by Incompleteusern** [comment]
That's true, but it would be better off not to save the data at all. Its probably fine though.

**Review by Incompleteusern — APPROVED** [review]

**Comment by magicus** [comment]
No, no! We must save it here. Otherwise we can't easily re-update the map tiles with journeymap in case something fails.

Doing *manual* editing of png files was one of the design mistakes with the Legacy map!

**Pull request merged**
