### PR TITLE
2.0 Mapping

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by magicus** [comment]
That was a lot of changed png:s! Have all of them really been updated for 2.0, or is there some part of the update process that causes this to look like a changed png even though it has not really changed?

**Comment by kristofbolyai** [comment]
I tried to check and I think Wynn just updated a lot of stuff.

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
Will you take the generated image from the script and upload it to Athena?

**Comment by kristofbolyai** [comment]
> Will you take the generated image from the script and upload it to Athena?

It is out already. In fact, I just pushed an even newer version, mapped on the bonfire ingame event. However since the event is temporary, I did not make a PR here.

**Pull request merged**
