### PR TITLE
Raw crowd sourced data from detection runs #2

### PR DESCRIPTION
**Pull request by kristofbolyai**
This is #6 but I parse the data from 07.11, not from Pyro, as Pyro's data is using an old version of Wynntils. I also added a new script.

### CODE REVIEW

**Comment by kristofbolyai** [comment]
@magicus

**Comment by kristofbolyai** [comment]
I commited https://github.com/Wynntils/Reference/commit/0550157f11fe3295cf38b31fd61cecef32a80ff3 as it is much better than the previous version.

**Comment by kristofbolyai** [comment]
New data has some things missing, but old data can't be trusted...

**Comment by kristofbolyai** [comment]
I think the newer versions can't parse certain NPCs... Like Party Finder

**Comment by kristofbolyai** [comment]
https://github.com/Wynntils/Reference/commit/55779cc4f4e99d692dc04e1a011dd5e5ba9ff37f fixup

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
@DevScyu I think you are the only one with write access to this repo? (Maybe that can be fixed)

**Comment by DevScyu** [comment]
> @DevScyu I think you are the only one with write access to this repo? (Maybe that can be fixed)

Added perms for mod-developers

**Pull request merged**
